db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/electronic_shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Colombo
db.user=root
# Change this if your MySQL root password is different
db.password=Rihan@123
